### ISSUE TITLE
[BUG] DeprecationWarnings in node v22 DEP0055 DEP0047 DEP0044

### ISSUE THREAD

**Issue by mdouglass** [node-config/node-config#765]
**Describe the bug**
On startup, we see multiple DeprecationWarnings from config.js calling `util.isArray`, `util.isRegExp` and `util.isDate`:

```
(node:2639986) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
1595.292626 warn: warning DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
    at _clone (/obscured/node_modules/config/lib/config.js:1006:15)
    at Config.cloneDeep (/obscured/node_modules/config/lib/config.js:1048:10)
    at /obscured/node_modules/config/lib/config.js:1323:32
    at Array.forEach (<anonymous>)
    at Config.util.extendDeep (/obscured/node_modules/config/lib/config.js:1298:9)
    at /obscured/node_modules/config/lib/config.js:653:12
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (/obscured/node_modules/config/lib/config.js:650:16)
    at new Config (/obscured/node_modules/config/lib/config.js:116:27)
    at Object.<anonymous> (/obscured/node_modules/config/lib/config.js:1515:33)
(node:2639986) [DEP0055] DeprecationWarning: The `util.isRegExp` API is deprecated. Please use `arg instanceof RegExp` instead.
1600.924325 warn: warning DeprecationWarning: The `util.isRegExp` API is deprecated. Please use `arg instanceof RegExp` instead.
    at _clone (/obscured/node_modules/config/lib/config.js:1008:22)
    at Config.cloneDeep (/obscured/node_modules/config/lib/config.js:1048:10)
    at /obscured/node_modules/config/lib/config.js:1323:32
    at Array.forEach (<anonymous>)
    at Config.util.extendDeep (/obscured/node_modules/config/lib/config.js:1298:9)
    at /obscured/node_modules/config/lib/config.js:653:12
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (/obscured/node_modules/config/lib/config.js:650:16)
    at new Config (/obscured/node_modules/config/lib/config.js:116:27)
    at Object.<anonymous> (/obscured/node_modules/config/lib/config.js:1515:33)
(node:2639986) [DEP0047] DeprecationWarning: The `util.isDate` API is deprecated.  Please use `arg instanceof Date` instead.
1601.225412 warn: warning DeprecationWarning: The `util.isDate` API is deprecated.  Please use `arg instanceof Date` instead.
    at _clone (/obscured/node_modules/config/lib/config.js:1011:22)
    at Config.cloneDeep (/obscured/node_modules/config/lib/config.js:1048:10)
    at /obscured/node_modules/config/lib/config.js:1323:32
    at Array.forEach (<anonymous>)
    at Config.util.extendDeep (/obscured/node_modules/config/lib/config.js:1298:9)
    at /obscured/node_modules/config/lib/config.js:653:12
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (/obscured/node_modules/config/lib/config.js:650:16)
    at new Config (/obscured/node_modules/config/lib/config.js:116:27)
    at Object.<anonymous> (/obscured/node_modules/config/lib/config.js:1515:33)
```

**Expected behavior**
No deprecation warnings when starting on node v22.

### Please tell us about your environment:

 -  node-config version: 3.3.11
 -  node-version: 22.1.0
 
### Other information
I'm happy to submit a PR to make the recommended changes but wanted to make sure it was OK to do so first as I don't know how it would fit in with your back-compat strategy for previous node.js versions.

Thanks!

**Comment by mdouglass** [comment]
Fixed by #764
